NEU_Health:
  enable: False
  trigger:
    enable: False
    cron: "40 7,12,19 * * * " # 分 时 天 周 月
  account:
    -
      studentID: ''
      password: 
      channel:
        serverChan:
          enable: False
          sckey: 
pterclub:
  enable: False
  trigger:
    enable: False
    cron: "30 0 * * * " # 分 时 天 周 月
  account:
    -
      cookies: ""
      channel:
        serverChan:
          enable: False
          sckey: 
hdatmos:
  enable: False
  trigger:
    enable: False
    cron: "30 0 * * * " # 分 时 天 周 月
  account:
    -
      cookies: ""
      channel:
        serverChan:
          enable: False
          sckey: 
smzdm:
  enable: False
  trigger:
    enable: False
    cron: "30 0 * * * " # 分 时 天 周 月
  account:
    -
      cookies: ""
      channel:
        serverChan:
          enable: False
          sckey: 
config:
  log: 
    level: INFO # DEBUG,INFO,WARNING,ERROR,CRITICAL
    file: logs/error.log # Adapter For Baota Panel
  push:
    global:
      sendMsgOnlyError: True
    channel:
      mail:
        enable: False
        receiver: ''
        sender: ''
        password: ''
        host: ''
        port: ''
      serverChan:
        enable: False
        sckey: 